[package]
name = "overtopr"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.36.1"
clearscreen = "4.0.2"
byte-unit = "5.1.6"
ctrlc = "3.5.1"
crossterm = "0.29.0"
# procfs = "0.18.0"
# zbus_systemd = {version = "0.25701.0", features=["network1"]}
# zbus = "5.7.1"